services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 7900:3000
    volumes:
      - ./config:/app/config # Diretorio onde serao armazenadas as configuracoes
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) integracao com docker
    # user: 1000:1000 optional, not compatibile with direct socket see https://gethomepage.dev/en/configs/docker/#using>
    restart: unless-stopped