version: '3.1'
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./uptime-kuma/data:/app/data
    container_name: uptime-kuma
