version: '3.5'
services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8080:8080  # Para trocar a porta mude somente o que ha antes dos dois pontos
      - 8443:8443
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080 || exit 1"] # Altere a URL para o seu cenario
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s